### ISSUE TITLE
port date2secs and secs2date from Chandra.Time?

### ISSUE THREAD

**Issue by jzuhone** [sot/cxotime#5]
The functions `date2secs` and `secs2date` from `Chandra.Time` are quick and useful. Is there a speed advantage over the class `CxoTime` which would make it useful to port them here in some way?

**Comment by jzuhone** [comment]
ping @taldcroft

**Comment by taldcroft** [comment]
I've finished one upstream performance fix for astropy (https://github.com/astropy/astropy/pull/10406) and am working on another https://github.com/astropy/astropy/pull/10360.

The goal is that `CxoTime(date).secs` and `CxoTime(secs).date` are just natively fast enough. But of course dedicated methods that assume the right formats and go straight to ERFA will be faster, but I'm not sure how much faster.

**Comment by taldcroft** [comment]
If you are interested, I can point you to some of the astropy code that does all the heavy lifting with just a couple of ERFA library calls.  There is a ton of cruft around it that could mostly be cut out.

**Comment by jzuhone** [comment]
Of course if `CxoTime` is fast enough by itself, it may satisfy portability to just have functions for `date2secs` and `secs2date` to wrap `CxoTime(date).secs` and `CxoTime(secs).date.`
